### ISSUE TITLE
Error Right Click

### ISSUE THREAD

**Issue by DAD713** [hilleer/vscode-yaml-plus-json#16]
Installed extension, opened a json file and right clicked.  Received error below.

WIndows 10,  Code v1.44.2

Command 'Convert to YAML' resulted in an error (command 'extension.rightClickJson' not found)

**Comment by hilleer** [comment]
Hi @DAD713,

I am not able to reproduce your issue using the same vscode version on windows 10.

If you have not done so already, can you try to reload vscode and try agian?

If that does not help, can you try to:

1. Click on **help**.
2. Click on **toggle developer tools**.
3. Use the command and copy the error from the console here.

**Comment by hilleer** [comment]
Hi @DAD713 ,

Have you had the time to try what I suggested above? :-)

**Comment by DAD713** [comment]
I will try again in the morning

Thanks
Joe

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hilleer** [comment]
Hi @DAD713 ,

Did you have a chance to try again?

**Comment by DAD713** [comment]
Maybe I'm using it wrong. 

Re-Installed extension

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Error "Failed to parse YAML.  Please make sure it has a valid format and try again'

[test.zip](https://github.com/hilleer/vscode-yaml-plus-json/files/4695967/test.zip)

**Comment by hilleer** [comment]
@DAD713 thanks - I will try to reproduce again and create a fix :)

**Comment by hilleer** [comment]
Hi @DAD713 ,

sorry for the late response.

I have been trying to reproduce but I don't have any issues converting the file you have attached.

If you open the vscode developer console, it should have printed a more detailed error. Is it possible for you to copy + paste that here (_help_ --> _toggle developer tools_)?

**Comment by hilleer** [comment]
Closing for now as I cannot reproduce and as no response has been given. Will re-open and work on a fix if any new information is provided.
