### ISSUE TITLE
Feature Request - indentation options

### ISSUE THREAD

**Issue by surveyplanetdev** [hilleer/vscode-yaml-plus-json#23]
There should be an option to specify how many spaces should be used for YAML indentation. The plugin uses 2 but that's not part of the [specifications](https://yaml.org/spec/1.2/2009-07-21/spec.html#id2576668).

**Comment by hilleer** [comment]
Hi @surveyplanetdev ,

please find this feature from version >= 1.4.0: https://github.com/hilleer/vscode-yaml-plus-json/releases/tag/v1.4.0.

See [README](https://github.com/hilleer/vscode-yaml-plus-json/releases/tag/v1.4.0) for details.
