### ISSUE TITLE
Feature request: allow undo, do not do immediate in-place conversion

### ISSUE THREAD

**Issue by natesilva** [hilleer/vscode-yaml-plus-json#26]
Currently this extension instantly converts your file from YAML to JSON, renames the file extension, and deletes the YAML file. There is no way to undo the changes (other than revert from Git).

Converting a file from JSON back to YAML is not sufficient, because you lose all the comments.

It would be better if there were an option to convert the file but not save it. That way the user could decide to save the changes, or hit Cmd-Z (Ctrl-Z) to undo the changes.

One use case, besides the obvious “oops - undo” use case, is this: I find the YAML format confusing. Sometimes I want to see if I’ve written proper YAML by temporarily converting my document to JSON to verify that it is correct. Then I want to revert back by hitting Cmd-Z, which should preserve my *original* YAML including any comments.

**Comment by hilleer** [comment]
Hi @natesilva,

Interesting idea. I think that makes a lot of sense :-) 

My initial thought about a solution would be to add one of the vscode buttons (in the bottom right corner) to "revert". What do you think about that solution?

**Comment by natesilva** [comment]
Would it preserve the YAML comments? a revert button would be great.

**Comment by hilleer** [comment]
@natesilva my idea was to keep the YAML that was converted from in memory - so if one "revert" it would:

1. Remove the _converted to_ json file.
2. Recreated the _converted from_ yaml file.

**Comment by hilleer** [comment]
Hi @natesilva ,

I have published [version 1.5.0](https://github.com/hilleer/vscode-yaml-plus-json/releases/tag/v1.5.0) that includes your requested feature.

Please notify me if you happen to notice any issues.

**Comment by natesilva** [comment]
This works great, thanks! The revert button is perfect.

**Comment by hilleer** [comment]
@natesilva Amazing! Glad you like it :)
