### ISSUE TITLE
Feature Request - Preserve original file

### ISSUE THREAD

**Issue by Joe136** [hilleer/vscode-yaml-plus-json#30]
When I convert the file into the other format (eg YAML -> JSON) from the context menu, the original file will be deleted.
https://github.com/hilleer/vscode-yaml-plus-json/blob/8af588cfd958c0fee7b171c592ef7d1c7d26a9ad/src/onRightClick.ts#L107
In case I need the original file, use the generated file as intermediate file or just experimenting with the output, it is practical to have both versions (original and generated).

At the moment I convert it from command line; being able to do it with mouse / F1 will make this task much faster. I would appreciate this feature, because I want to get rid of json/jsonc/json5 in the future.

**Comment by sarimarton** [comment]
I'd love this feature too. I'm working with a complex Karabiner Elements config, for which json is unbearably cumbersome, so I need to switch to YAML source. I need something which generates out the json target.

**Comment by hilleer** [comment]
Hi @Joe136 @sarimarton 

I am happy to announce that I have published a new version `1.9.0` with this feature. Please see the [README](https://github.com/hilleer/vscode-yaml-plus-json/tree/v1.9.0#keep-original-files) for details.

Please do not hesitate to get in touch if you find any problems or open new issues, if you have new feature requests!
