### ISSUE TITLE
命令"Convert selection to YAML"导致错误 (command 'extension.jsonSelectionToYaml' not found)

### ISSUE THREAD

**Issue by geekyouth** [hilleer/vscode-yaml-plus-json#37]
**Describe the bug**
命令"Convert selection to YAML"导致错误 (command 'extension.jsonSelectionToYaml' not found)

**To Reproduce**
1. Create a text json with content :
2. Use command :
![image](https://user-images.githubusercontent.com/12899262/117904779-92426d00-b304-11eb-8d17-adbb36aeec3e.png)
3. See error
![image](https://user-images.githubusercontent.com/12899262/117904805-9ec6c580-b304-11eb-9499-8f8339292854.png)

**Screenshots**
see above.

**(please complete the following information):**
 - OS: Windows 10 专业工作站版
 - Version 20H2
 - Vscode version 1.56.1
 - Extension version v1.7.0

![image](https://user-images.githubusercontent.com/12899262/117905010-00872f80-b305-11eb-8e38-4dfd79f44169.png)

**Comment by hilleer** [comment]
Hi @geekyouth 

I have published version `1.8.0` that adds additional `activationEvents` for scenarios where a json or yaml file is not present in the workspace on vscode startup.

I hope this resolve your issue, otherwise please reach out.
