### ISSUE TITLE
Render JSON preview from YAML 

### ISSUE THREAD

**Issue by cleder** [hilleer/vscode-yaml-plus-json#43]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to see what a YAML file looks like serialized to JSON,
or the other way round. Useful when learning the YAML Syntax - and bug hunting ;-)

**Describe the solution you'd like**
Similar to the preview feature of `.md` files, open another pane with the JSON generated from the YAML or vice versa

**Describe alternatives you've considered**
It's more like a nice to have, there are workarounds, might be an easy win?

**Comment by hilleer** [comment]
Hi @cleder 

Thanks for opening this issue!
Interesting idea. Should definitely be doable and not too difficult.

**Comment by hilleer** [comment]
Hi @cleder 

I am happy to announce that I have released version `1.10.0` with this feature, implemented by those changes https://github.com/hilleer/vscode-yaml-plus-json/pull/48.
