### ISSUE TITLE
Allow us to disable success popup

### ISSUE THREAD

**Issue by ssbarnea** [hilleer/vscode-yaml-plus-json#49]
**Describe the bug**

The success popup is noisy and many people would want to just disable it.

**To Reproduce**
Convert a file.

**Expected behavior**
Popups should appear only on warnings and errors, not on successes.

**Screenshots**
**Additional context**

BTW, Thanks for writing this extension.

**Comment by hilleer** [comment]
Hi @ssbarnea 

Thanks for reporting/requesting this. I will look into adding a config for such 🙂

**Comment by hilleer** [comment]
Hi @ssbarnea 

Sorry for not implementing related to your issue sooner.

I have published version `1.11.0` that will no longer show an information message, after successfully doing revert of converted files. This was the only information file that is currently not used for another purpose, as far as I found.

I plan another configuration to disable information messages to show "revert" option.

Please let me know if you find any other concerns in relation to this.

Have a nice sunday!

**Comment by ssbarnea** [comment]
I will test it. BTW, if you want you could consider contributing this feature into https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml - i can help you get it in.
