### ISSUE TITLE
Publish this VSCode extension also in open-vsx.org

### ISSUE THREAD

**Issue by elgalu** [hilleer/vscode-yaml-plus-json#52]
Would it be possible that you publish this VSCode extension also in https://open-vsx.org/

This would make it much easier to use the extension in project such as

* [gitpod.io](https://gitpod.io/)
* [theia-ide.org](https://theia-ide.org/)
* [VS Codium](https://vscodium.com/)
* [code-server](https://github.com/cdr/code-server)

thanks in advance

**Comment by hilleer** [comment]
Hi @elgalu 

Thanks for opening this issue with this suggestion.
I was not aware of this cool project. I can definitely have a look into it adding it there too 🙂

**Comment by hilleer** [comment]
Hello @elgalu 

Happy to announce I have successfully published a version of the extension in the open-vsx registry. You can find it [here](https://open-vsx.org/extension/hilleer/yaml-plus-json).

Please let me know if you find any issues installing it. Notice I am also currently in the process of _claiming the namespace_, so you will (currently) see a warning that the account is not verified.

Please do not hesitate to create new issues for bugs or feature requests.

And thanks again for suggesting this.
