### ISSUE TITLE
request for bulk json to yaml operation (and vica versa)

### ISSUE THREAD

**Issue by Cerberussian** [hilleer/vscode-yaml-plus-json#9]
Hi,

I had a folder with 50+ json files I wanted to convert and couldn't find a way to do it.
Tried renaming files to yml but its not detected automatically.

Would be very useful to have option to convert files in bulk.

Thanks!

/enhancement

**Comment by hilleer** [comment]
Hi @Cerberussian ,

Thanks for the issue.

That sounds a bit cumbersome to convert one by one :-) I can totally look into adding that feature.

What is your personal preference of activating such feature? Right click and a context menu or a command palette command?

**Comment by Cerberussian** [comment]
Best scenario for me would be right clicking on a folder and choosing to convert to json / yml. If I chose json for example, I'd expect all json files to stay json in that folder and all yaml / yml files in that folder to be converted to json.

Another scenario that can be useful is selecting multiple files and choosing to convert them.

Thanks!

**Comment by hilleer** [comment]
@Cerberussian sounds good to me. I'll try to find some time asap to look into adding that feature - it does not sound too complicated :) I will keep you updated.

**Comment by hilleer** [comment]
Hi @Cerberussian ,

I have published [version 1.1.0](https://github.com/hilleer/vscode-yaml-plus-json/releases/tag/v1.1.0) to include the requested feature. You can use it right clicking a directory and selecting the appropriate convertion.

Please let me know if you have any issues using it or comments to add.

**Comment by hilleer** [comment]
Hi @Cerberussian ,

I have published [version 1.2.0](https://github.com/hilleer/vscode-yaml-plus-json/releases/tag/v1.2.0) now to include the feature to convert a range of selected items.

Again, please let me know if you have any issues or comments to add. Do not hesitate to open a new issue with additional feature requests :-)

Happy easter!

**Comment by Cerberussian** [comment]
Works awesome! Thanks!
